#!/bin/bash

WINDOW_HEIGHT=30
WINDOW_WIDTH=125

main()
{
	while [ 1 ]
	do
		SECIM=$(whiptail --title "Olasılık ve İstatistik" \
		--ok-button "Seç" --cancel-button "Çıkış" \
		--menu "Seçeneklerden birini seçiniz:" \
		${WINDOW_HEIGHT} ${WINDOW_WIDTH} 3>&1 1>&2 2>&3 14 \
		"1" "Elaman Sayısı" \
		"2" "Diziyi Sırala" \
		"3" "Aritmetik Ortalama" \
		"4" "Harmonik Ortalama" \
		"5" "Geometrik Ortalama" \
		"6" "Medyan" \
		"7" "Mod" \
		"8" "Ortalama Sapma" \
		"9" "Standart Sapma" \
		"10" "Varyans" \
		"11" "Değişim Katsayısı" \
		"12" "Permütasyon" \
		"13" "Kombinasyon" \
		"14" "Frekans"
		)
		
		if [ $? = 1 ]
		then
			break
		fi

		# Adet
		if [ ${SECIM} -eq 1 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --adet)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Eleman Sayısı" 3>&1 1>&2 2>&3

		# Sirala
		elif [ ${SECIM} -eq 2 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --sirala)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Sıralanmış Dizi" 3>&1 1>&2 2>&3

		# Aritmetik Ortalama
		elif [ ${SECIM} -eq 3 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --aritmetik-ortalama)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Aritmetik Ortalama" 3>&1 1>&2 2>&3

		# Harmonik Ortalama
		elif [ ${SECIM} -eq 4 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --harmonik-ortalama)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Harmonik Ortalama" 3>&1 1>&2 2>&3

		# Geometrik Ortalama
		elif [ ${SECIM} -eq 5 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --geometrik-ortalama)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Geometrik Ortalama" 3>&1 1>&2 2>&3

		# Medyan
		elif [ ${SECIM} -eq 6 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --medyan)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Medyan" 3>&1 1>&2 2>&3

		# Mod
		elif [ ${SECIM} -eq 7 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --mod)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Mod" 3>&1 1>&2 2>&3

		# Ortalama Sapma
		elif [ ${SECIM} -eq 8 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --ortalama-sapma)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Ortalama Sapma" 3>&1 1>&2 2>&3

		# Standart Sapma
		elif [ ${SECIM} -eq 9 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --standart-sapma)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Standart Sapma" 3>&1 1>&2 2>&3

		# Varyans
		elif [ ${SECIM} -eq 10 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --varyans)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Varyans" 3>&1 1>&2 2>&3

		# Degisim Katsayısı
		elif [ ${SECIM} -eq 11 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --degisim-katsayisi)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Değişim Katsayısı" 3>&1 1>&2 2>&3

		# Permütasyon
		elif [ ${SECIM} -eq 12 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --permutasyon)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Permütasyon" 3>&1 1>&2 2>&3

		# Kombinasyon
		elif [ ${SECIM} -eq 13 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --kombinasyon)

			whiptail --msgbox "Cevabınız: ${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Kombinasyon" 3>&1 1>&2 2>&3

		# Frekans
		elif [ ${SECIM} -eq 14 ]
		then
			sayi_al

			if [ $? = 1 ]
			then
				continue
			fi

			echo ${DIZI[@]} > "whiptail-girdi.txt"

			CEVAP=$(./olasilik -d "whiptail-girdi.txt" --frekans)

			whiptail --msgbox "Cevabınız:\n${CEVAP}" ${WINDOW_HEIGHT} \
			${WINDOW_WIDTH} --title "Frekans" 3>&1 1>&2 2>&3
		fi
	done
}

sayi_al()
{
	DIZI=$(whiptail --inputbox "Hesaplamak istediğiniz diziyi girin:" \
	     ${WINDOW_HEIGHT} ${WINDOW_WIDTH} --title "Olasılık ve İstatistik" \
	     --ok-button "Hesapla" --cancel-button "Vazgeç" \
         3>&1 1>&2 2>&3)
}

main
